import { ANALYTE_ALIASES } from "./analyteAliases";
import { normalizeName } from "./normalize";
import type { AnalyteDef } from "./types";

const createDef = (
  display: string,
  category?: AnalyteDef["category"],
  preanalyticRisk?: AnalyteDef["preanalyticRisk"],
): AnalyteDef => ({
  id: normalizeName(display),
  display,
  normalized: normalizeName(display),
  aliases: ANALYTE_ALIASES[display],
  category,
  preanalyticRisk,
});

const RAW_DEFS: Array<[string, AnalyteDef["category"]?, AnalyteDef["preanalyticRisk"]?]> = [
  ["1,7-dimethylxanthine", "Exposure", "Medium"],
  ["2-aminobutyric", "Redox"],
  ["2-hydroxy-2-methylbutyric", "BCAA"],
  ["2-hydroxybutyric", "Redox"],
  ["2-hydroxyisocaproic", "BCAA"],
  ["2-hydroxyisovaleric", "BCAA"],
  ["2-methylcitric", "Redox"],
  ["2-oxobutyric", "Redox"],
  ["2-oxoglutaric", "Energy"],
  ["2-oxoisocaproic", "BCAA"],
  ["2-oxoisovaleric", "BCAA"],
  ["3-hydroxy-2-methylbutyric", "BCAA"],
  ["3-hydroxy-3-methylglutaric", "BCAA"],
  ["3-hydroxybutyric", "Energy", "High"],
  ["3-hydroxyisobutyric", "BCAA"],
  ["3-hydroxyisovaleric", "BCAA"],
  ["3-hydroxypropionic", "Gut"],
  ["3-methylcrotonylglycine", "BCAA"],
  ["3-methylcytidine", "Exposure"],
  ["3-methylglutaconic", "BCAA"],
  ["3-methylglutaric", "BCAA"],
  ["4-hydroxybutyric", "CNS"],
  ["4-hydroxyhippuric", "Gut"],
  ["4-hydroxyphenylacetic", "Gut"],
  ["4-hydroxyphenylpyruvic", "Gut"],
  ["4-hydroxyphenyllactic", "Gut"],
  ["5-HIAA", "CNS"],
  ["5-methylcytidine", "Exposure"],
  ["5-oxoproline", "Redox"],
  ["Aconitic-Z", "Energy"],
  ["ADMA", "Vascular"],
  ["acetoacetic", "Energy", "High"],
  ["acetylcholine", "CNS"],
  ["acetylcarnitine", "FAO"],
  ["adipic", "FAO", "High"],
  ["alpha-aminobutyric", "Redox"],
  ["arabitol", "Gut"],
  ["arginine", "Methylation"],
  ["azelaic", "FAO"],
  ["benzoic", "Gut"],
  ["betaine", "Methylation"],
  ["dopamine", "CNS"],
  ["epinephrine", "CNS"],
  ["butyrate", "Gut", "Medium"],
  ["butyrylcholine", "CNS"],
  ["butyrylcarnitine", "FAO"],
  ["cadaverine", "Gut"],
  ["carnitine", "FAO"],
  ["cinnamoylglycine-trans", "Gut"],
  ["citric", "Energy"],
  ["citrulline", "Methylation"],
  ["creatine", "Energy"],
  ["creatinine", "Kidney", "High"],
  ["cystathionine", "Methylation"],
  ["cysteinylglycine", "Redox"],
  ["decanoylcarnitine", "FAO"],
  ["dimethylglycine", "Methylation"],
  ["dodecanedioic", "FAO"],
  ["folate", "Methylation"],
  ["fumaric", "Energy"],
  ["GABA", "CNS"],
  ["galactitol", "Gut"],
  ["gamma-butyrobetaine", "FAO"],
  ["glycine", "Methylation"],
  ["glycochenodeoxycholic", "Liver"],
  ["glycocholic", "Liver"],
  ["glycodeoxycholic", "Liver"],
  ["glucuronic acid", "Liver"],
  ["guanidinoacetic", "Energy"],
  ["hexanoylcarnitine", "FAO"],
  ["hexanoylglycine", "FAO"],
  ["hippuric", "Gut"],
  ["homoarginine", "Vascular"],
  ["homocitrulline", "Methylation"],
  ["homogentisic", "Gut"],
  ["homocysteine", "Methylation"],
  ["HVA", "CNS"],
  ["indole-3-acetic", "Gut"],
  ["indole-3-aldehyde", "Gut"],
  ["indole-3-butyric", "Gut"],
  ["indole-3-carboxylic", "Gut"],
  ["indole-3-propionic", "Gut"],
  ["indole-3-pyruvic", "Gut"],
  ["indolelactic", "Gut"],
  ["isocitric", "Energy"],
  ["isoleucine", "BCAA"],
  ["kynurenic", "CNS"],
  ["kynurenine", "CNS"],
  ["L-DOPA", "CNS"],
  ["lauroylcholine", "CNS"],
  ["lauroylcarnitine", "FAO"],
  ["leucine", "BCAA"],
  ["malic", "Energy"],
  ["mannitol", "Gut"],
  ["melatonin", "CNS"],
  ["methylmalonic", "Methylation"],
  ["MHPG", "CNS"],
  ["myristoylcholine", "CNS"],
  ["myristoylcarnitine", "FAO"],
  ["N-acetyl-tyrosine", "CNS"],
  ["NAD+", "Redox", "High"],
  ["neopterin", "Exposure"],
  ["norepinephrine", "CNS"],
  ["octanoylcarnitine", "FAO"],
  ["ornithine", "Methylation"],
  ["orotic acid", "Liver"],
  ["palmitoylcarnitine", "FAO"],
  ["paraxanthine", "Exposure", "Medium"],
  ["phenylacetic", "Gut"],
  ["phenylalanine", "Gut"],
  ["phenylpyruvic", "Gut"],
  ["phenyllactic", "Gut"],
  ["tryptamine", "CNS"],
  ["tryptophan", "CNS"],
  ["tyramine", "CNS"],
  ["tyrosine", "CNS"],
  ["propionate", "Gut", "Medium"],
  ["propionylcholine", "CNS"],
  ["propionylcarnitine", "Redox"],
  ["propionylglycine", "Redox"],
  ["pseudouridine", "Exposure"],
  ["quinolinic", "CNS"],
  ["ribitol", "Gut"],
  ["ribothymidine", "Exposure"],
  ["ribulose", "Gut"],
  ["SAH", "Methylation"],
  ["SAM", "Methylation"],
  ["sarcosine", "Methylation"],
  ["sebacic", "FAO"],
  ["serine", "Methylation"],
  ["serotonin", "CNS"],
  ["SDMA", "Kidney", "High"],
  ["sorbitol", "Gut"],
  ["spermidine", "Gut"],
  ["spermine", "Gut"],
  ["stearoylcarnitine", "FAO"],
  ["suberic", "FAO"],
  ["suberylglycine", "FAO"],
  ["succinic", "Energy"],
  ["succinic semialdehyde", "CNS"],
  ["tetradecanedioic", "FAO"],
  ["theobromine", "Exposure"],
  ["theophylline", "Exposure"],
  ["THF", "Methylation"],
  ["tiglylglycine", "BCAA"],
  ["trimethylamine", "Gut", "High"],
  ["trimethylamine-N-oxide", "Gut", "High"],
  ["trimethyl-lysine", "Methylation"],
  ["tridecanedioic", "FAO"],
  ["undecanedioic", "FAO"],
  ["uric", "Kidney"],
  ["valine", "BCAA"],
  ["VMA", "CNS"],
  ["xanthosine", "Exposure"],
  ["xylitol", "Gut"],
];

export const ANALYTE_REGISTRY: AnalyteDef[] = RAW_DEFS.map(([display, category, risk]) =>
  createDef(display, category, risk),
);

export const ANALYTE_BY_NORMALIZED = new Map<string, AnalyteDef>();
ANALYTE_REGISTRY.forEach((def) => {
  ANALYTE_BY_NORMALIZED.set(def.normalized, def);
  (def.aliases ?? []).forEach((alias) => {
    const normalizedAlias = normalizeName(alias);
    if (!ANALYTE_BY_NORMALIZED.has(normalizedAlias)) {
      ANALYTE_BY_NORMALIZED.set(normalizedAlias, def);
    }
  });
});
