export const ANALYTE_ALIASES: Record<string, string[]> = {
  "3-hydroxybutyric": ["beta-hydroxybutyrate", "b-hydroxybutyrate", "bhb"],
  "2-oxoglutaric": ["alpha-ketoglutarate", "a-ketoglutarate", "akg"],
  "5-oxoproline": ["pyroglutamic", "pyroglutamate", "pyroglutamic acid"],
  "Aconitic-Z": ["cis-aconitate", "aconitic acid"],
  "1,7-dimethylxanthine": ["17-dimethylxanthine"],
  "trimethylamine-N-oxide": ["tmao"],
  trimethylamine: ["tma"],
  dimethylglycine: ["dmg"],
  "5-HIAA": ["5-hydroxyindoleacetic acid"],
  GABA: ["gamma-aminobutyric acid"],
  "L-DOPA": ["ldopa", "levodopa"],
  HVA: ["homovanillic acid"],
  VMA: ["vanillylmandelic acid"],
  MHPG: ["3-methoxy-4-hydroxyphenylglycol"],
  SAH: ["s-adenosylhomocysteine"],
  SAM: ["s-adenosylmethionine"],
  THF: ["tetrahydrofolate"],
  arginine: ["l-arginine", "arginine", "arg", "ARG"],
  citrulline: ["l-citrulline", "citrulline_free", "citrulline"],
  ornithine: ["l-ornithine", "ornithine"],
};
